#!/usr/bin/env node
// Renders references/tables.md from trusted-layer.json, the table allowlist
// the cohort column predicate is checked against. Deterministic: the same
// allowlist always renders the same bytes, so a test can hold the committed
// file to the data.
//
// Usage: node render-tables.cjs           rewrite ../references/tables.md
//        node render-tables.cjs --check   exit 1 when the file is stale
'use strict';
const {readFileSync, writeFileSync} = require('node:fs');
const {join} = require('node:path');
const {TABLES, OPS_BY_KIND, VALUE_HINT, VIRTUAL_COLUMNS, OUTCOMES, MAX_DEPTH, MAX_LEAVES, MAX_IN_VALUES, columnKind} = require('./validate-predicate.cjs');

const OUTPUT = join(__dirname, '..', 'references', 'tables.md');

// The type class shown to readers. Zoned and zone-less timestamps take the
// same ops and the same literal rules, so they share one class here.
const CLASS_OF_KIND = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  timestamp: 'timestamp',
  timestamp_ntz: 'timestamp',
  date: 'date',
  complex: 'complex',
};
const CLASSES = ['string', 'number', 'boolean', 'timestamp', 'date', 'complex'];
const CLASS_KIND = {string: 'string', number: 'number', boolean: 'boolean', timestamp: 'timestamp', date: 'date', complex: 'complex'};

const code = text => `\`${text}\``;
const opList = kind => OPS_BY_KIND[kind].map(code).join(', ');

function availability(entry) {
  return entry.available === false
    ? 'not yet in the lake: refused (any predicate on this table is rejected)'
    : 'available';
}

function tableSection(name, entry) {
  const lines = [`## ${name}`, ''];
  lines.push(`- Call id column: ${code(entry.callId)}`);
  lines.push(`- Tenant column: ${entry.tenant ? code(entry.tenant) : 'none'}`);
  lines.push(`- Date column: ${code(entry.dateColumn)}`);
  if (entry.callIdWhere) lines.push(`- Row filter: only rows where ${code(entry.callIdWhere.column)} = ${code(entry.callIdWhere.equals)}`);
  lines.push(`- Cost: ${entry.cost}`);
  lines.push(`- Availability: ${availability(entry)}`);
  lines.push(name === 'calls'
    ? `- Reference as: ${code('<column>')} or ${code('calls.<column>')}`
    : `- Reference as: ${code(`${name}.<column>`)}`);
  lines.push('');
  if (name === 'calls') {
    lines.push('### Virtual columns', '');
    lines.push('Computed per call, not stored. Bare names only: `calls.outcome` does not resolve.', '');
    lines.push('| Column | Ops | Value |', '| --- | --- | --- |');
    for (const [column, kind] of Object.entries(VIRTUAL_COLUMNS)) {
      lines.push(`| ${code(column)} | ${opList(kind)} | ${VALUE_HINT[kind]} |`);
    }
    lines.push('');
  }
  const denied = new Set(entry.deny);
  const usable = Object.keys(entry.columns).filter(c => !denied.has(c)).sort();
  lines.push('### Usable columns', '');
  lines.push('| Column | Class | Ops |', '| --- | --- | --- |');
  for (const column of usable) {
    const kind = columnKind(entry.columns[column]);
    lines.push(`| ${code(column)} | ${CLASS_OF_KIND[kind]} | ${opList(kind)} |`);
  }
  lines.push('');
  lines.push('### Denied columns', '');
  lines.push(denied.size === 0 ? 'None.' : [...denied].sort().map(code).join(', '));
  lines.push('');
  return lines;
}

function renderTables() {
  const entries = Object.entries(TABLES).map(([name, entry]) => ({name, entry}));
  entries.sort((a, b) => (a.name === 'calls' ? -1 : b.name === 'calls' ? 1 : a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  const lines = [
    '# Predicate tables',
    '',
    '> Generated by `scripts/render-tables.cjs` from `scripts/trusted-layer.json`.',
    '> Do not edit by hand. Re-cut both files when the API\'s predicate allowlist',
    '> changes; the plugin tests fail when this page and the data disagree.',
    '',
    'Every table and column a cohort `where` leaf may name. A table not listed here',
    'is refused as `unknown or unallowlisted table`; a listed column under',
    '"Denied columns" is refused as `denied column`. The API is the authority if',
    'it has moved ahead of this copy.',
    '',
    '## Type classes',
    '',
    '| Class | Ops | Value |',
    '| --- | --- | --- |',
    ...CLASSES.map(cls => `| ${cls} | ${opList(CLASS_KIND[cls])} | ${VALUE_HINT[CLASS_KIND[cls]]} |`),
    '',
    `- \`in\` and \`not_in\` take a non-empty array of at most ${MAX_IN_VALUES} values, every one of the class's value type.`,
    '- `is_null` and `is_not_null` take no `value` at all.',
    '- `contains` takes a non-empty string.',
    '- A timestamp value needs a `Z` or numeric offset and at most three fractional digits; a date value must be a real calendar day.',
    '- A complex column (arrays, maps, structs) can only be tested for null.',
    '- Refusal messages name a zone-less timestamp column\'s class `timestamp_ntz`; it takes the same ops and values as `timestamp`.',
    `- A predicate nests at most ${MAX_DEPTH} levels deep and holds at most ${MAX_LEAVES} leaves.`,
    `- \`outcome\` values: ${OUTCOMES.map(code).join(', ')}.`,
    '',
    '## Cost',
    '',
    'A predicate is heavy when any leaf reads a heavy table, light otherwise.',
    'Virtual columns read `calls` and are light.',
    '',
  ];
  for (const {name, entry} of entries) lines.push(...tableSection(name, entry));
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

module.exports = {renderTables, OUTPUT};

if (require.main === module) {
  const rendered = renderTables();
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(OUTPUT, 'utf8'); } catch { /* missing counts as stale */ }
    if (current !== rendered) {
      console.error('references/tables.md is stale; run node scripts/render-tables.cjs');
      process.exit(1);
    }
    process.exit(0);
  }
  writeFileSync(OUTPUT, rendered);
  console.log(`wrote ${OUTPUT}`);
}
